### ISSUE TITLE
Broken CMake

### ISSUE THREAD

**Issue by dutkalex** [DLR-AMR/t8code#1041]
Hi!
I wanted to try out the new 2.0 version but it seems like the CMake build system is broken:
```
CMake Error at src/CMakeLists.txt:2 (add_library):
  Cannot find source file:

    t8_cmesh/t8_cmesh.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:2 (add_library):
  No SOURCES given to target: T8


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Maybe some refactoring was done which impacted the file structure recently?
Best regards,
Alex

**Comment by dutkalex** [comment]
File globing is a code smell IMHO and this is only the tip of the iceberg: `p4est` has improved their build system and the changes have not been accounted for in `t8code`, and the double `libsc` pull now breaks the configuration step.
From what @holke and @jmark told me at the time (#919, #929, #956), having a working CMake build system for `t8code` was a goal of yours. This is concerning for dependent projects which forbid the use of autotools and therefore rely on the CMake build system. 
What is your policy regarding this issue? Can't this simply be checked with a Github action? 
I would rather like not having to fork just to be able to build reliably... (and safely)

**Comment by sandro-elsweijer** [comment]
Hey @dutkalex,
I think there was a misunderstanding. We will move towards the CMake build system and we will support it. For now, we consider it an experimental feature. Since there is no CI integration **yet**, it is possible that it breaks.
And instead of adding files manually, we want to activate file globbing. Furthermore, we will integrate it in our CI, but it has not happened yet. We already have a person working on it, but it will take some time.

**Comment by dutkalex** [comment]
@sandro-elsweijer thanks for clearing this up. I understand better your previous answer now, and if you plan on major restructurings of the code base I understand the rationale for temporarily enabling file globing... In the meantime, I am working on fixing the issues in p4est and libsc so that dependent projects can safely build on top of them.

**Comment by sandro-elsweijer** [comment]
@dutkalex Thank you for your understanding. Can you elaborate on why you think file globbing isn't a good idea?
Ant thank you for your contributions! Next Monday we will assign your PR to somebody so that it can get a quick review.
