### ISSUE TITLE
Coding style guidelines: Allow for C++ style comments: `// ...`

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#1078]
As of now, t8code [guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline#comments) enforce the old C commenting style `/* ... */`.

I propose to relax this.

# Why?

## An excerpt from here: https://github.com/mcinglis/c-style?tab=readme-ov-file#use--comments-everywhere-never---
Stick to single-line comments, and cut the complexity. Compared to single-line comments, multi-line comments:

- are rarely used with a blank margin, so they're just as character-heavy
- have a style, which has to be specified and adhered to
- often have `*/` on its own line, so they're more line-expensive
- have weird rules about embedded `/*` and `*/`
- are harder/impossible to block-edit, and to extend
- are more visually-cluttering than `//`

You have to use `/* ... */` for inline comments in multi-line `#define`s, though:

``` c
#define MAGIC( x ) \
    /* Voodoo magic happens here. */ \
    ...
```

**Comment by Davknapp** [comment]
Follwing our Developer Meeting we allow C++-Style comments from now on.
