### ISSUE TITLE
I'm building t8code on macos, but I fail the test/t8_forest_incomplete/t8_gtest_iterate_replace

### ISSUE THREAD

**Issue by CFDER-HF** [DLR-AMR/t8code#1083]
[config.log](https://github.com/user-attachments/files/15818108/config.log)

**Comment by holke** [comment]
Thank you for reporting this.
This has never occurred before and we will investigate.

If you do not need the incomplete forest feature (I.e. removing elements from the mesh) we recommend to deactivate the test case for the time being.

You can do so by either using the DISABLED or GTEST_SKIP keywords: https://stackoverflow.com/questions/7208070/googletest-how-to-skip-a-test

**Comment by Davknapp** [comment]
Can you add the log file of the failing test?

**Comment by holke** [comment]
This is probably related to #1093

**Comment by holke** [comment]
Hi @CFDER-HF, we fixed the issue in #1100 

It would be great if you could verify that it runs now.

This was more a bug in the test itself than a bug in t8code.

**Comment by CFDER-HF** [comment]
> Hi @CFDER-HF, we fixed the issue in #1100
> 
> It would be great if you could verify that it runs now.
> 
> This was more a bug in the test itself than a bug in t8code.

Sorry for the late reply--your helpful and timely reply is beyond my expectation!  I just had another try and it passed the test successfully. Thanks a lot!
