### ISSUE TITLE
Todos for the new CMake CI

### ISSUE THREAD

**Issue by sandro-elsweijer** [DLR-AMR/t8code#1133]
The CMake CI had to do some shortcuts, because it is still missing some features. Here is a list:

- [x] NetCDF linkage: The test is ready and can be uncommented when NetCDF linkage becomes available
- [x] WError checking: WError (and maybe also WPedantic) has to be enabled to throw errors for warnings
- [x] Enable less tests: The enable less tests option was not available and has to be set as soon as it becomes available

**Comment by holke** [comment]
@jmark and @maelk3 please check if these are fulfilled now.

**Comment by maelk3** [comment]
#1140 fullfills the third bullet point.

**Comment by jmark** [comment]
https://github.com/DLR-AMR/t8code/pull/1154 fullfills second bullet point.
