### ISSUE TITLE
Confusing t8code compile flags reporting

### ISSUE THREAD

**Issue by maelk3** [DLR-AMR/t8code#1147]
Currently, t8code's initialization gives the following output:

```
[t8] This is t8 2.0.0-449-g5e1d6acf5
[t8] CPP                      /tools/modulesystem/spack-22.2/opt/spack/linux-ubuntu20.04-x86_64_v3/gcc-9.4.0/gcc-11.3.0-avy3yt67apn6ntfapginc4al4misogxc/bin/g++
[t8] CPPFLAGS                 -Wall -O2 -g -DNDEBUG
[t8] CC                       /tools/modulesystem/spack-22.2/opt/spack/linux-ubuntu20.04-x86_64_v3/gcc-9.4.0/gcc-11.3.0-avy3yt67apn6ntfapginc4al4misogxc/bin/gcc
[t8] CFLAGS                   -Wall -O2 -g -DNDEBUG
[t8] LDFLAGS                  
[t8] LIBS                     P4EST::P4EST SC::SC MPI::MPI_C
```

However, I think that `CPPFLAGS` should be renamed to `CXXFLAGS` as it can be mistaken with the C PreProcessor flags (by convention the `CPPFLAGS` variable for Makefiles is intended for the c preprocessor and not the c++ compiler). `CPP` should also be renamed `CXX` IMHO. Is there any reason to keep those variables the way they currently are ?

**Comment by jmark** [comment]
This makes perfect sense to me.

**Comment by maelk3** [comment]
However, with the autotools build system, I get:
```
[t8] CPP                      mpicc -E
[t8] CPPFLAGS                 
[t8] CC                       mpicc
[t8] CFLAGS                   -O0
[t8] LDFLAGS                  
[t8] LIBS                     -lz -lm  -lstdc++
```

This time, `CPP` refers to the c preprocessor and `CPPFLAGS` c preprocessor flags. @jmark Do you know what is supposed to be the correct behavior between the two build systems?

**Comment by jmark** [comment]
@maelk3 We go with `CXX`. Autotools is not our gold standard. ;)
