### ISSUE TITLE
More detail on contributing

### ISSUE THREAD

**Issue by jwallwork23** [DLR-AMR/t8code#1161]
The "Contributing" section at the start of `CONTRIBUTING.md` is very brief. It would be beneficial to provide a little more detail on:
 a) How to contact principal developers (if you want to make a large contribution).
 b) Provide a link to the coding guidelines [wiki page](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).
 c) Whether there are requirements for all new contributions to be tested and documented. I notice there is a wiki page on this but it isn't linked from `CONTRIBUTING.md` nor the coding guidelines [wiki page](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline).

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by holke** [comment]
Thank you for this input.

It is very beneficial for us to have a good CONTRIBUTING file.
We will adress your changes.

**Comment by holke** [comment]
Please see #1172. I hope i addressed all your concernces.
I added further info, linked the Wiki article on Coding guidelines and also updated the Wiki article.

**Comment by holke** [comment]
Issue got closed automatically but id like to wait for your feedback before closing.

**Comment by jwallwork23** [comment]
> Please see #1172. I hope i addressed all your concerns. I added further info, linked the Wiki article on Coding guidelines and also updated the Wiki article.

Thanks for addressing this - it's really useful to have this extra detail. Happy for this issue to be closed.
