### ISSUE TITLE
Tutorials "Build cmesh" and "Search algorithm" compilation

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code#1175]
Hi,

I am testing the tutorials (Apple M1) and, thanks to your precious support, I was able to successfully run until step7 using commands like:
`mpicxx t8_step7*.cxx t8_step3_adapt_forest.cxx -I$HOME/t8code/t8code_build/local/include -L$HOME/t8code/t8code_build/local/lib -lt8 -lp4est -lsc -lm -lz`

If I try the same approach with "Build Cmesh" and "Search algorithm" I get many errors and warning, so before posting long error messages, how should I properly compile those ones if I want to compile them alone manually? Does the procedure change?

Thank you very much!
Best,
Alessandro Contri

**Comment by holke** [comment]
Hi @alecontri and thank you for asking.

The step examples are not intended to be build on their own but to be built together with t8code when invoking `make`.
I added a text to the [Turorials Wiki page](ehttps://github.com/DLR-AMR/t8code/wiki/Tutorial---Overview) to clarify this.

**Comment by holke** [comment]
Should you not find the executables after `make` then something went wrong and we should investigate.

**Comment by alecontri** [comment]
Ok, thanks a lot for the info :) yes the executable are all correctly placed, have a good day!

**Comment by alecontri** [comment]
Closed since solved

**Comment by holke** [comment]
Great, thanks :)
