### ISSUE TITLE
Find a new script to indent our source code

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#12]
We are currently using the GNU `indent` script, however it is actually not designed for
`C++` codes and hence causes some malfunctions there (For example adding an extra const to const functions, which then causes compiler errors).

We should (at least for `C++` files) switch to a different indent program.

**Comment by holke** [comment]
`astyle` seems to be a good choice.
I am currently figuring out the settings that come closest to the existing `indent` settings.

**Comment by holke** [comment]
`clang-format` is a good choice as well.

The main challenge is to find settings that come as close to the current indent settings as possible.
Unfortunately, i was not able to reproduce them completely, neither with astyle nor clang-format.

**Comment by chiaraMaHe** [comment]
still open

**Comment by cburstedde** [comment]
What's the closest in settings that y'all could find? I'd like to experiment. This will be good for p4est and libsc as well.

**Comment by sandro-elsweijer** [comment]
@cburstedde 
here is the clang-format file I created:
https://github.com/DLR-AMR/t8code/blob/feature-new_script_to_indent_our_source_code/.clang-format
Here is also a nice online tool describing all available options:
https://zed0.co.uk/clang-format-configurator/

**Comment by sandro-elsweijer** [comment]
We switched to clang format
