### ISSUE TITLE
New wiki-entry about reproducing our scaling results

### ISSUE THREAD

**Issue by Davknapp** [DLR-AMR/t8code#1210]
# Feature request

Following the discussion in #1184 we want to move the description about how to reproduce our scaling results. 

**Is your feature request related to a problem? Please describe.**
A reviewer had difficulties to verify our scaling results. This should be easy to do. 

**Describe the solution or feature you'd like**
A good description in our wiki might help. It is very accessible and probably one of the first points one might look for help. @holke explanation is already a good starting point. 

**Describe alternatives you've considered**

**Estimated priority**

"Priority: medium"  Should be solved within half a year 

**Additional context**

**Comment by holke** [comment]
This is the description David is referring to: https://github.com/DLR-AMR/t8code/issues/1184#issuecomment-2273384130

**Comment by ole-alb** [comment]
I added a wiki article [Reproducing Scaling Results](https://github.com/DLR-AMR/t8code/wiki/Reproducing-Scaling-Results)
