### ISSUE TITLE
CI: Activate "enable-fortran" in our CI tests

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#1214]
# Feature request

**Is your feature request related to a problem? Please describe.**
We are currently adding a fortran interface. With #1182 we now have a configure option "--enable-fortran" and a CMake option should follow.
These are currently not tested in our CI, which also excludes all possible future Fortran related test cases.

**Describe the solution or feature you'd like**
Test the "enable-fortran" option in our CI.
I would suggest adding it to all test cases by default.

Should we also consider testing one version with "disable-fortran"?

**Describe alternatives you've considered**
Not testing is not an option.

**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: medium"  Should be solved within half a year 

**Additional context**

**Comment by holke** [comment]
Yes, havent seen that before. I guess #1204 will adress this.

**Comment by sandro-elsweijer** [comment]
@holke I already implemented it for the CMake build system, but there the cmake flag is not yet implemented. I will not implement it for the autotools CI.
