### ISSUE TITLE
Recursive adapt should also partition

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#132]
Add an option to set_adapt to partition when recursive is on.
Otherwise, load-imbalances may occur when adapting.

**Comment by ililikakis** [comment]
So it should be partitioned during the recursive adapt?

**Comment by cburstedde** [comment]
> So it should be partitioned during the recursive adapt?

For demos/applications I tend to recommend a loop around { non-recursive
adapt; partition; }.

**Comment by holke** [comment]
We will not implement additional functionality to that.
If you need partitioning during recursive adapt, the adapt should be split in different steps with intermediate partitioning,
For example:

- adapt recursively for 3 levels
- stop, partition the forest
- adapt for 3 more levels
- stop, partition the forest
and so on.

This can be implemented by users with existing functionalities.
