### ISSUE TITLE
VTK library warnings

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#169]
When linking against VTK using `--with-vtk` the VTK library prints many compiler warnings.

Mostly of the form
```
vtkXMLPUnstructuredDataWriter.h:36:65: warning: extra ‘;’ [-Wpedantic]
   vtkTypeMacro(vtkXMLPUnstructuredDataWriter, vtkXMLPDataWriter);
```

We should suppress these warnings since

1. They clutter the console log and hide important warnings
2. As soon as we have a test case that links against VTK, the automatic test suite will not compile due to using `-Werror`

One way is to disable '-Wpedantic' before each VTK include and enable it later.

This needs to be done in a compiler independent manner.

**Comment by holke** [comment]
Related to #250

**Comment by sandro-elsweijer** [comment]
This currently stops the development of #553

**Comment by sandro-elsweijer** [comment]
I have tried using the 
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
    #include <some_vtk_header.h>
#pragma GCC diagnostic pop
```
method, but this did not work. Therefore, I will link the VTK libs with `-isystem` instead of `-I`, as suggested here: https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers
But this does not solve the general Problem

**Comment by sandro-elsweijer** [comment]
I tried using this method
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
    #include <some_vtk_header.h>
#pragma GCC diagnostic pop
```
for all included VTK headers, but this had no effect on the VTK warnings.
Therefore, I will use `-isystem` instead of `-I` for configuring as suggested here: https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers
This does not solve this issue completely, but it solves the CI part.

**Comment by sandro-elsweijer** [comment]
Oops, there were some connection problems

**Comment by sandro-elsweijer** [comment]
The compiler warnings are disabled when using `-isystem` instead of "-I" to link against vtk
