### ISSUE TITLE
Implement NCA for pyramids

### ISSUE THREAD

**Issue by Davknapp** [DLR-AMR/t8code#184]
The computation of the nearest common ancestor is not implemented for pyramids. This is important to support to the ghost algorithm v3

**Comment by Davknapp** [comment]
Done in feature-NCA_for_pyramids.
PR, as soon as feature-pyramid_element is merged into develop

**Comment by holke** [comment]
We should only close issues when the feature is integrated at least into develop.
Once the PR is open we can link this issue to be closed automatically when merged.
