### ISSUE TITLE
Add at least one pure C example

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#232]
We should add at least one example that uses the C interface and is purely written in C.
This example should be a copy of an existing C++ example (maybe the basic example).

**Comment by jmark** [comment]
Actually, I also thought about C++ and C interface examples side by side. Something like 'step_02.c' and 'step_02.cxx' or
via '#if __cplusplus' in cases where appropiate.

**Comment by holke** [comment]
Yes, having (at least) one step example in a .c version is a good idea.
I would keep it as separate files, though.
