### ISSUE TITLE
Implement t8_forest_point_inside for quads

### ISSUE THREAD

**Issue by Davknapp** [DLR-AMR/t8code#268]
During PR #267 we realised that the implementation of this function is missing for quads. To solve this issue implement the function for quads.

**Comment by Flo1314** [comment]
A few weeks ago, I tried to make png2mesh compatible with t8code. By default, png2mesh uses the quad scheme for this function and therefore it did not work directly. As a hotfix, I just used the pyramid implementation of this function for quads and it worked perfectly fine. 

Reading the documentation of the pyramid approach there (comparing all normal vectors with the given point), I see no reason why this procedure should not work for quads as well - so maybe give it a try :)
