### ISSUE TITLE
Fix example t8_cmesh_load_and_refine

### ISSUE THREAD

**Issue by Davknapp** [DLR-AMR/t8code#275]
The example 'example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole' seems to be broken, gdb gave the following information:
'
Thread 1 "t8_load_and_ref" hit Breakpoint 3, t8_forest_get_eclass_scheme (forest=0x687690, eclass=T8_ECLASS_TRIANGLE) at ../t8code/src/t8_forest/t8_forest.c:1124
1124	  T8_ASSERT (t8_forest_is_committed (forest));
(gdb) where
#0  t8_forest_get_eclass_scheme (forest=0x687690, eclass=T8_ECLASS_TRIANGLE)
    at ../t8code/src/t8_forest/t8_forest.c:1124
#1  0x0000000000421ec6 in t8_forest_element_coordinate (forest=0x687690, ltree_id=0, 
    element=0x5d3800, corner_number=0, coordinates=0x696bd0)
    at ../t8code/src/t8_forest/t8_forest_cxx.cxx:210
#2  0x0000000000404dec in t8_midpoint (forest=0x687690, which_tree=0, ts=0x691640, 
    element=0x5d3800, elem_mid_point=0x7ffffffc9fd0, h=0x7ffffffc9fc8)
    at ../t8code/example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx:97
#3  0x0000000000404f92 in t8_load_refine_adapt (forest=0x687690, forest_from=0x6918b0, 
    which_tree=0, lelement_id=0, ts=0x691640, is_family=1, num_elements=4, elements=0x5cbb30)
    at ../t8code/example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx:126
#4  0x000000000041d33c in t8_forest_adapt (forest=0x687690)
    at ../t8code/src/t8_forest/t8_forest_adapt.cxx:321
#5  0x000000000041a751 in t8_forest_commit (forest=0x687690)
    at ../t8code/src/t8_forest/t8_forest.c:590
#6  0x0000000000405184 in t8_load_refine_build_forest (cmesh=0x5c8430, comm=1140850688, level=1)
    at ../t8code/example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx:170
#7  0x0000000000405292 in main (argc=1, argv=0x7ffffffca2b8)
    at ../t8code/example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx:201
(gdb) c
Continuing.
[libsc 0] Abort: Assertion 't8_forest_is_committed (forest)'
[libsc 0] Abort: ../t8code/src/t8_forest/t8_forest.c:1124
'

**Comment by sandro-elsweijer** [comment]
This seems to be fixed. Closing this issue
