### ISSUE TITLE
Improving the quality of comments.

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#300]
In the wiki page about coding guidelines I would also add more rules about commenting styles.
For example, I much prefer complete sentences with correct English grammar, spelling and punctuation.

Example:
```
/* This is a comment written as a complete sentence, ending with a dot
 * and maintaining proper margins (whitespaces) towards the '*' symbols. */
```

Of course, short statements resp. remarks are also ok. Something like
```
/* Checking for xyz. */
```

**Comment by holke** [comment]
Good point +1

**Comment by jmark** [comment]
BTW, is it also ok to use C++ style comments in `t8code`?
```
// This is a C++ style comment.
```

**Comment by jmark** [comment]
Added this in the Wiki.
