### ISSUE TITLE
How to interpret the face connectivity when reading a simple, flipped 2D mesh file with 2x2 elements?

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#318]
Reading a simple 2D mesh with 2x2 quadrangles yields wrong
face connectivity within the cmesh structure.

Geo file:
```
//+
Point(1) = {-1.0, -1.0, 0, 1.0};
//+
Point(2) = {1.0, -1.0, 0, 1.0};
//+
Point(3) = {-1.0, 1.0, 0, 1.0};
//+
Point(4) = {1.0, 1.0, 0, 1.0};
//+
Line(1) = {1, 3};
//+
Line(2) = {3, 4};
//+
Line(3) = {4, 2};
//+
Line(4) = {2, 1};
//+
Curve Loop(1) = {2, 3, 4, 1};
//+
Plane Surface(1) = {1};
//+
Transfinite Surface {1} = {3, 4, 2, 1};
//+
Transfinite Curve {2, 3, 4, 1} = 3;
//+
Recombine Surface {1};
```

Mesh file in 'msh' format, version 2 (Version 4 gives the same bug.):
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
9
1 -1 -1 0
2  1 -1 0
3 -1  1 0
4  1  1 0
5 -1  0 0
6  0  1 0
7  1  0 0
8  0 -1 0
9  0  0 0
$EndNodes
$Elements
16
1 15 2 0 1 1
2 15 2 0 2 2
3 15 2 0 3 3
4 15 2 0 4 4
5 1 2 0 1 1 5
6 1 2 0 1 5 3
7 1 2 0 2 3 6
8 1 2 0 2 6 4
9 1 2 0 3 4 7
10 1 2 0 3 7 2
11 1 2 0 4 2 8
12 1 2 0 4 8 1
13 3 2 0 1 3 6 9 5
14 3 2 0 1 5 9 8 1
15 3 2 0 1 6 4 7 9
16 3 2 0 1 9 7 2 8
$EndElements
```
Above mesh file describes the following 2x2 mesh.
Exported from `gmsh`. So it must be a valid mesh file.
```
(-1, 1)      ( 1, 1)
          
    3-----6-----4
    |  0  |  2  |
    5-----9-----7 
    |  1  |  3  |
    1-----8-----2
        
(-1,-1)      ( 1,-1)
```

Minimal working example:
```C++
#include <stdio.h>
#include <t8_cmesh.h>
#include <t8_cmesh/t8_cmesh_trees.h>
#include <t8_cmesh/t8_cmesh_types.h>
#include <t8_cmesh_readmshfile.h>

int main (int argc, char **argv) {

  int mpiret = sc_MPI_Init (&argc, &argv);
  SC_CHECK_MPI (mpiret);

  sc_MPI_Comm comm = sc_MPI_COMM_WORLD;

  sc_init (comm, 1, 1, NULL, SC_LP_ESSENTIAL);
  t8_init (SC_LP_DEFAULT);

  const char fileprefix[] = "square2x2_v2"; // Version 2. 
  // const char fileprefix[] = "square2x2_v4"; // Version 4. Same problem.

  t8_cmesh_t cmesh = t8_cmesh_from_msh_file (fileprefix, 0, comm, 2, 0, 0);

  t8_locidx_t num_local_trees = t8_cmesh_get_num_local_trees(cmesh);

  for (t8_locidx_t itree = 0, current_index = 0; itree < num_local_trees; ++itree) {

    t8_ctree_t tree = t8_cmesh_get_tree (cmesh, itree);

    t8_locidx_t *face_neighbor = (t8_locidx_t *) T8_TREE_FACE (tree);

    printf("face_neighbor[%d,%d] = %d\n",itree, 0, face_neighbor[0]);
    printf("face_neighbor[%d,%d] = %d\n",itree, 1, face_neighbor[1]);
    printf("face_neighbor[%d,%d] = %d\n",itree, 2, face_neighbor[2]);
    printf("face_neighbor[%d,%d] = %d\n",itree, 3, face_neighbor[3]);
    printf("\n");
  }
 
  t8_cmesh_unref (&cmesh);

  sc_finalize ();

  mpiret = sc_MPI_Finalize ();
  SC_CHECK_MPI (mpiret);
  return 0;
}
```

The output is
```
face_neighbor[0,0] = 0
face_neighbor[0,1] = 2
face_neighbor[0,2] = 0
face_neighbor[0,3] = 1

face_neighbor[1,0] = 1
face_neighbor[1,1] = 3
face_neighbor[1,2] = 0
face_neighbor[1,3] = 1

face_neighbor[2,0] = 0
face_neighbor[2,1] = 2
face_neighbor[2,2] = 2
face_neighbor[2,3] = 3

face_neighbor[3,0] = 1
face_neighbor[3,1] = 3
face_neighbor[3,2] = 2
face_neighbor[3,3] = 3
```

For the first element, for example, one might be tempted to actually define the connectivity to be:
```
face_neighbor[0,0] = 0  // x- face (boundary, referencing itself)
face_neighbor[0,1] = 2  // x+ face (element to the right)
face_neighbor[0,2] = 1  // y- face (element below)
face_neighbor[0,3] = 0  // y+ face (boundary, referencing itself)
```

**Comment by jmark** [comment]
It seems that the node ordering in the `gms` output files is not according to http://www.manpagez.com/info/gmsh/gmsh-2.2.6/gmsh_65.php#SEC65 .

Even the 1x1 mesh (just one element) has a strange node ordering:
```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
4
1 -0.5 -0.5 0
2 0.5 -0.5 0
3 -0.5 0.5 0
4 0.5 0.5 0
$EndNodes
$Elements
9
1 15 2 0 1 1
2 15 2 0 2 2
3 15 2 0 3 3
4 15 2 0 4 4
5 1 2 0 1 1 3
6 1 2 0 2 3 4
7 1 2 0 3 4 2
8 1 2 0 4 2 1
9 3 2 0 1 3 4 2 1
$EndElements
```

**Comment by jmark** [comment]
Opened an issue at `gmsh` developer page: https://gitlab.onelab.info/gmsh/gmsh/-/issues/2080

**Comment by jmark** [comment]
The response to issue https://gitlab.onelab.info/gmsh/gmsh/-/issues/2080 is:
> By specifying the corners of the transfinite interpolation you explicitly request the orientation of the mesh (here opposite to the underlying orientation of the surface).

Hence, valid mesh files (from gmsh) can have surfaces with opposite orientation which leads to reversed node numbering, i.e. 
clockwise instead of counter-clockwise according to the documentation in https://gmsh.info/doc/texinfo/gmsh.html#Node-ordering.

**Comment by jmark** [comment]
For completness. The following geo script gives the expected node ordering:
```
// Gmsh project created on Mon Aug 29 09:18:02 2022
//+
Point(1) = {0, 0, 0, 1.0};
//+
Point(2) = {1, 0, 0, 1.0};
//+
Point(3) = {1, 1, 0, 1.0};
//+
Point(4) = {0, 1, 0, 1.0};
//+
Line(1) = {1, 2};
//+
Line(2) = {2, 3};
//+
Line(3) = {3, 4};
//+
Line(4) = {4, 1};
//+
Curve Loop(1) = {1, 2, 3, 4};
//+
Plane Surface(1) = {1};
//+
Transfinite Surface {1} = {1, 2, 3, 4};
//+
Transfinite Curve {1, 3} = 1 Using Progression 1;
//+
Transfinite Curve {2, 4} = 1 Using Progression 1;
//+
Recombine Surface {1};
```

**Comment by holke** [comment]
looking at your first file again and following up our discussion on this:
With the current specifications t8code should be able to read the file and produce the correct mesh.

The only convention that needs to be fulfilled is a clockwise or anticlockwise orderin of the nodes (as opposed to a Z or X wise ordering). 
It should neither matter at which vertex we start nor whether we go clockwise or anticlockwise. Since the 2D Quad is embedded in 3D space and we allow for arbitrary translation and rotation in 3D.

So it seems that somehow our face matching gets confused with this example.

**Comment by holke** [comment]
mhmm. but the 2D logical vertices should then get assigned 3D coordinates which would flip the element around again...?

**Comment by jmark** [comment]
It turned that `gmsh` can create meshes where the node ordering is reversed. This is due to the effect that the reference coordinate system is flipped in one dimension. It is not considered a bug and is valid behavior. `t8code` simply copies this convention and passes this through to the client application. Hence, the client application has to expect this behavior and has to act accordingly.
