### ISSUE TITLE
`t8_cmesh_set_partition_uniform` does not work when geometry is committed only on the master rank

### ISSUE THREAD

**Issue by sandro-elsweijer** [DLR-AMR/t8code#352]
The example `example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole` crashes in parallel, and it seems to have something to do with the partitioning of geometries. If the cmesh is build by a main rank and the geometry is also only committed on the main rank, the geometry of the trees is not found by the other processes after calling `t8_cmesh_set_partition_uniform`.

**Comment by holke** [comment]
The geometries must be registered on all processes.
It is not possible to register a geometry on one rank only and then "send" it to the other procs.

Setting the geometry of a specific tree can and should be carried out by a single process, namely the process owning this tree.

In the example the geometries are only registered on the main rank and hence it breaks.

Two main adaptations are required

- [ ] Adapt the Gmsh reader (and every other code that registeres geometries) such that the geoms are registered on all procs.
- [ ] Extend the documentation of the geometry Modul, especially the involved functions, such that the behavior becomes clear

**Comment by holke** [comment]
Addition:

If the registration of the geometry really was the problem then the user should get informed about this.
- [ ] An error message "geometry not found" and a controlled shutdown should occur even in non debug mode.

**Comment by lukasdreyer** [comment]
The solution that was introduced in https://github.com/DLR-AMR/t8code/pull/380 did not work on partitioned cmeshes.
This was because of https://github.com/DLR-AMR/t8code/issues/428, so when that is fixed, https://github.com/DLR-AMR/t8code/pull/380 can be merged again to close this issue.
