### ISSUE TITLE
Remove processing of linear geometries for speedup

### ISSUE THREAD

**Issue by sandro-elsweijer** [DLR-AMR/t8code#399]
The curved geometry evaluation processes all geometry types, even if they are linear or planar. It would bring performance benefits to just omit these geometries

**Comment by holke** [comment]
i do not really understand what you mean.
Can you clarify?
I dont understand how the curved geometry should realize that a tree is not curved if it is marked as using the occ geometry.

**Comment by sandro-elsweijer** [comment]
In OpenCASCADE the geometries are realized in different classes, and it is possible to check, if the underlying geometry is, for example, a planar geometry. We could implement a small check in the curved msh file input, which only links the geometry to the trees, if they are not planar. Then we would save the computational effort in the geometry evaluations later on

**Comment by holke** [comment]
sounds good :)

**Comment by holke** [comment]
Please check whether death test are really not supported.
If not, we should update our MPI Gtest to the 1.10 version: https://github.com/DLR-SC/googletest_mpi/tree/GoogleTest_MPI-1.10.0

This version should work with death tests (but not in parallel!).

**Comment by holke** [comment]
Please check whether death test are really not supported.
If not, we should update our MPI Gtest to the 1.10 version: https://github.com/DLR-SC/googletest_mpi/tree/GoogleTest_MPI-1.10.0

This version should work with death tests (but not in parallel!).
