### ISSUE TITLE
A vertex is always a family

### ISSUE THREAD

**Issue by ililikakis** [DLR-AMR/t8code#412]
```t8_default_scheme_vertex_c::t8_element_is_family (*)``` always returns 1, even if the level is 0.
This way we run into ```T8_ASSERT (tscheme->t8_element_level (elements_from[0]) > 0)``` in ```t8_forest_adapt (*)```.
I would suggest changing the return in ```t8_dvertex_is_familypv (*)``` from 0 to ```f[0]->level > 0```.

**Comment by holke** [comment]
Yes, i just checked with the other element shapes and we had the implicit assumption that a level 0 element is not a family.
This is a kind of philosophical question and there are definitely arguments for a level 0 element being a family.

Let us

- [ ] Clearly state in the documentation of the is_family functions that a level 0 element will never be a family
- [ ] Return 0 for all level 0 elements including vertices

**Comment by ililikakis** [comment]
Sounds good! It has to be the same rule for all elements.
You can assign me to this issue.
