### ISSUE TITLE
Pyramid volume bug

### ISSUE THREAD

**Issue by jfussbro** [DLR-AMR/t8code#438]
![grafik](https://user-images.githubusercontent.com/71825121/220382498-a63d35ff-824d-49c0-936e-8829da1385fc.png)

I came across the bug that different volumes are computed for identical pyramid elements. The problem doesn't occur with different element types (e.g. prisms). I have created a branch with a minimal working example of the bug. The example is contained in the file named "t8_practice_file" (https://github.com/jfussbro/t8code/blob/pyra_volume_bug/tutorials/general/t8_practice_file.cxx).

**Comment by holke** [comment]
pinging @Davknapp since he might be interested

**Comment by holke** [comment]
Can you elaborate what you mean with "identical pyramids"?
Identical in that the same node numbering same coordinates per node result in different volumes for different calls of the computation?

Or rotated and translated. So different orientation in space, but should have the same volume?
I guess the second one as in the added picture?

**Comment by jfussbro** [comment]
You are right with the second one. All three pyramids should be identical in terms of their volume but as the picture shows the volume is quite different for all three. According to the fact that the cube has an edge length of 1 the volume of all three pyramids should be around 0.33.

**Comment by holke** [comment]
Thanks for the reply :)

We should write a test case that cover this - so that when we fix the bug, we can directly check it.

**Comment by holke** [comment]
Related to #390
