### ISSUE TITLE
Adapt curved geometry evaluation to p4est edge numeration

### ISSUE THREAD

**Issue by sandro-elsweijer** [DLR-AMR/t8code#446]
I introduced an edge numbering for the linking of geometries and it differs slightly from the p4est numeration. Since the p4est numeration is more consistent, the curved geometries should be adapted

**Comment by cburstedde** [comment]
> I introduced an edge numbering for the linking of geometries and it differs slightly from the p4est numeration. Since the p4est numeration is more consistent, the curved geometries should be adapted

Cool.  I agree -- having more than one convention in the code may be an
expensive path to follow.  The p4est (and t8code face) convention does not
require global orientation and is transparent to periodicity.

**Comment by ililikakis** [comment]
Please also remove the suffixes in `t8_eclass.c` https://github.com/DLR-AMR/t8code/blob/main/src/t8_eclass.c#L46-L95 as mentioned in the TODOs.
