### ISSUE TITLE
Partitioned input from TRIANGLE does not work.

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#46]
Reading a mesh created with the TRIANGLE mesh generator with the partitioned flag on does not work.

How to replicate:

Use the `example/triangle/t8_read_triangle` example to read the example mesh `A.1.*` (Coming with TRIANGLE, can be build with `triangle -pne A.1`) with the `-p` option.

```bash
./t8_read_triangle -f A.1 -p
...
[libsc 0] Abort: Assertion 'num_trees == cmesh->num_trees'
[libsc 0] Abort: ../../source/t8code-second-worktree/src/t8_cmesh/t8_cmesh_partition.c:198
```

**Comment by holke** [comment]
TODO: This possibly extends to TETGEN input. This needs to be tested.

**Comment by sandro-elsweijer** [comment]
We won't support TRIANGLE anymore hence nobody uses this feature.
