### ISSUE TITLE
Release tarballs/zips are not compilable

### ISSUE THREAD

**Issue by jmark** [DLR-AMR/t8code#471]
I suspect that the release tarballs/zips in https://github.com/DLR-AMR/t8code/releases
are done automatically via the github interface. Although convenient, this just mirrors
the git repository without any `configure` script.

Normally in release tarballs/zips the `configure` script is already included and
can be run by the user.

If, alternatively, we want the user to run `./bootstrap` it does not work, since
`git submodule init` also does not work, since the releases are not a git repo.

Hence, the current releases are useless.

Interesting to see, that up to this time, no bug reports from users reached us.
Probably, all of the users clone the github repo anyway.

**Comment by cburstedde** [comment]
> I suspect that the release tarballs/zips in https://github.com/DLR-AMR/t8code/releases
> are done automatically via the github interface. Although convenient, this just mirrors
> the git repository without any `configure` script.
> 
> Normally in release tarballs/zips the the `configure` script is already included and
> can be run by the user.
> 
> If, alternatively, we want the user to run `./bootstrap` it does not work, since
> `git submodule init` also does not work, since the releases are not a git repo.
> 
> Hence, the current releases are useless.
> 
> Interesting to see, that up to this time, no bug reports from users, reached us.
> Probably, all of the users clone the github repo anyway.

We have been mentioning this fact on the p4est website for a long time.
Sometimes people are annoyed.  Especially checking out the submodules does
not work out of the box with the github mechanism.  Unclear whether fixable.

**Comment by jmark** [comment]
Pretty annoying. I just tried it out. You can attach arbitrary binary files to releases.
