### ISSUE TITLE
Linking to vtk with --use-vtk

### ISSUE THREAD

**Issue by jfussbro** [DLR-AMR/t8code#524]
I had the problem that linking with vtk didn't work using the recommended configure options in our wiki article:
`
--with-vtk 
--with-vtk_version_number=9.1 
LDFLAGS=-L$HOME/opt/vtk_install/lib 
CPPFLAGS=-I$HOME/opt/vtk_install/include/vtk-9.1
`
After removing the `--with-vtk` command (only using `--with-vtk_version_number=9.1`) linking worked again.

We should check if that is a bug or if the wiki article should be updated.

**Comment by holke** [comment]
Are you really sure that your version is linked against VTK with this option?

What is the output of the vtk linkage test?

Is the macro T8_WITH_VTK defined?

**Comment by jfussbro** [comment]
You are right... The output is `checking for VTK library... not used`, so the linking doesn't work properly
