### ISSUE TITLE
Tutorial step 4: no ghost cells in output 

### ISSUE THREAD

**Issue by bgeihe** [DLR-AMR/t8code#576]
First of all: Thanks for the great tutorial! It is a huge help for first-time users like myself.

What I noticed is that in step 4 of the tutorial there are not ghost cells in the output vtk files.

It can easily be fixed by using 
`t8_forest_write_vtk_ext (forest, prefix_partition_ghost, 1, 1, 1, 1, 1, 0, 0, 0, NULL);`
instead of 
`t8_forest_write_vtk (forest, prefix_partition_ghost);`
(which you learn in step 5).

Certainly not a big issue, but maybe you want to change it.

**Comment by sandro-elsweijer** [comment]
The `t8_forest_write_vtk` function is just a wrapper for `t8_forest_write_vtk_ext` function with some pre-set options. Would you like to do a PR with that?

**Comment by bgeihe** [comment]
Yes, I will. I already promised @jmark to do so...
