### ISSUE TITLE
Standardize Configure Option Description

### ISSUE THREAD

**Issue by chiaraMaHe** [DLR-AMR/t8code#584]
The description of the configure option in the Wiki and in the Code section are different.
In the Wiki it is for example described to do the bootstrap command from the git folder. In the code section it is written:

1.) If you cloned from github, initialize and download the git submodules
   p4est and sc.
  - git submodule init
  - git submodule update      
**2.) Call the bootstrap script in the source directory
  - ./bootstrap**        
3.) Goto your installation folder and call configure and make
  - cd /path/to/install
  - /path/to/source/configure [OPTIONS]
  - make 
  - make check
  - make install

We should check if there are other points that are different. There were problems because it is not clear if it should be called from the src folder or the git folder. - Do we need two descriptions. Wouldnt it be enough to link the Wiki?

**Comment by Davknapp** [comment]
To avoid confusion we should call the "installation"-folder "build"-folder.
