### ISSUE TITLE
[CRITICAL] T8CODE IS NOT BUILDABLE ON NEW FORKS

### ISSUE THREAD

**Issue by sandro-elsweijer** [DLR-AMR/t8code#589]
Newer forks (e.g. https://github.com/Tabea-leistikow/t8code) are not compilable, because the `git describe` command, which is used by configure to determine the version number, returns an error. This does not seem to be an issue with older forks (https://github.com/sandro-elsweijer/t8code). Maybe we can use a different command than `git describe` to determine the version of the repository.

Expected output of `git describe`:
```
user@computer:~/source/t8code$ git describe
v1.2.0-287-g0ffe4898
```
Error:
```
user@computer:~/source/t8code$ git describe
fatal: No names found, cannot describe anything.
```

**Comment by Davknapp** [comment]
Try 
```
git fetch --tags upstream
```
(for this the upstream has to be defined)
 Then execute
 ```
 git push --tags
 ```

**Comment by sandro-elsweijer** [comment]
I will add a note about that in the installation instructions when I am back in office

**Comment by cburstedde** [comment]
Yes, git describe requires the version tags to be present.
