### ISSUE TITLE
Serial CI job doesn't complain about MPI macros

### ISSUE THREAD

**Issue by lukasdreyer** [DLR-AMR/t8code#611]
There is a CI job without MPI enabled, but even though there was usage of `MPI_INT` instead of `sc_MPI_INT` in the code, the job compiled without error.
The problem only occured on a workstation with manual compilation, but should also be detected by the CI.

See: https://github.com/DLR-AMR/t8code/pull/610

**Comment by sandro-elsweijer** [comment]
The new CI catched the error. I will link this Issue to the PR of the new CI
https://github.com/DLR-AMR/t8code/actions/runs/5462301199/jobs/9941473478
