### ISSUE TITLE
Return value t8_forest_get_user_data

### ISSUE THREAD

**Issue by chiaraMaHe** [DLR-AMR/t8code#627]
In `t8_forest.c` there is the function` t8_forest_get user_data(*)`.
The return value is a void pointer. Using templates/classes could make this simpler.

```
void               *
t8_forest_get_user_data (t8_forest_t forest)
{
  return forest->user_data;
}
```

**Comment by jmark** [comment]
If we would stay in C++ world only then yes, this might be a way to make things much cleaner.

However, `t8code` is also supposed to be linked to software written in C or other programming languages. For that,
we need simple interfaces written in C. This is a technical limitation we have to account for.

Moreover, a void pointer gives maximum flexiblity what it points to. It can even be a datastructure/object/whatever from another
programming language.

**Comment by sandro-elsweijer** [comment]
@jmark  Wouldn't it be possible to use templates and have another templated function, which returns a void pointer for every object it gets? This way we could use templates for C++ specific things and use the "converter" function for everything else
