### ISSUE TITLE
Getting Face Neighbor IDs; Memory Leak in `t8_forest_leaf_face_neighbors` function.

### ISSUE THREAD

**Issue by ackirby88** [DLR-AMR/t8code#672]
I was wondering if there is a much faster way for **only** obtaining element-neighbor ID numbers rather than `t8_forest_leaf_face_neighbors`? This function is pretty slow and I believe has memory leaks.

I did a test tracking the memory usage (using `mallinfo` on linux; see my `memory_usage` function below) repeatedly calling this function  with the appropriate T8_FREE calls on the output variables (following the advect example) and found the memory keeps increasing. 

For a simple test using the advect example (example/advect/t8_advection.cxx -- lines 1147-1153), you can call my `memory_usage` function before `t8_forest_leaf_face_neighbors` and after you free the following variables: `neighbors`, `elem_data->dual_faces`, and `elem_data->neighs`. The memory should remain constant but doesn't.

Related to issue #142 and pull request #596.

```
/* file: memory_usage.h
 *   >> captures the number of bytes used by malloc
 */

// NOTE: LINUS ONLY

/* system header files */
#  include <math.h>
#  include <stdio.h>
#  include <stdlib.h>
#  include <malloc.h>

static inline
double
memory_usage(int display){
    /* get malloc info structure */
    struct mallinfo my_mallinfo = mallinfo();

    /*total memory reserved by the system for malloc currently */
    double reserved_mem = (double) my_mallinfo.arena;

    /* get all the memory currently allocated to user by malloc, etc. */
    double used_mem = (double) my_mallinfo.hblkhd
                  + (double) my_mallinfo.usmblks
                  + (double) my_mallinfo.uordblks;

    /* get memory not currently allocated to user but malloc controls */
    double free_mem = (double) my_mallinfo.fsmblks
                  + (double) my_mallinfo.fordblks;

    /* Print out concise malloc info line */
    if (display) {
        printf(stdout,"MEMORY USAGE: %f MB(%.0f) malloc: %f MB reserved (%.0f unused)\n",
              used_mem / (1024.0 * 1024.0),
              used_mem,
              reserved_mem / (1024.0 * 1024.0),
              free_mem);
    }
    return used_mem;
}
```

**Comment by ackirby88** [comment]
Okay, I think the leak is in `t8_forest_cxx.cxx` for the function `t8_forest_element_face_neighbor`. The `face_element` is not freed at the end of the function. So at line 2026, there should be `boundary_scheme->t8_element_destroy (1, &face_element);`

**Comment by lukasdreyer** [comment]
Hey Andrew, thank you for opening the issue!

I agree with you that the `face_element` should be destroyed in the end of the `t8_forest_leaf_face_neighbors` function.
Normally in t8code, it is checked by using the SC library, that every malloc is matched by a corresponding free. In this case unortunately, a memory pool is used, that frees all still used elements in the end. Thus, this problem was not discovered before.

I am currently investigating if we can catch such cases earlier in our automated testing.

In the meantime, I would already like to merge the fix into `main`. Are you interested to create a corresponding merge request?

Furthermore, as you already saw in #596, there are some ideas to improve the functionality of `t8_forest_leaf_face_neighbors`, so I am interested to hear your requirements for such a functionality. I'd like to work together with you in improving the user experience with t8code.

**Comment by ackirby88** [comment]
@lukasdreyer Absolutely, I can submit the pull request with the fix.

I've also noticed other (significant) memory issues arising from adapting the forest by checking the memory usage during a do-nothing refinement (i.e., simply replacing a forest by an identical forest). But the issues are much harder to pin down (but I'll keep working at it). From a user perspective, memory management is mission-critical as we normally do thousands of mesh adaptions in a single run.

With regards to #596, it would be great to be able to pass NULL values into that function to indicate what values are not needed, and thus skipping those calculations, which reemphasizes what @holke described in issue #142. The current pull request #596 only addresses the user-allocated memory requirements.

**Comment by lukasdreyer** [comment]
> I was wondering if there is a much faster way for **only** obtaining element-neighbor ID numbers rather than `t8_forest_leaf_face_neighbors`? This function is pretty slow and I believe has memory leaks.

> With regards to https://github.com/DLR-AMR/t8code/pull/596, it would be great to be able to pass NULL values into that function to indicate what values are not needed, and thus skipping those calculations, which reemphasizes what @holke described in issue https://github.com/DLR-AMR/t8code/issues/142. The current pull request https://github.com/DLR-AMR/t8code/pull/596 only addresses the user-allocated memory requirements.

Regarding your original question: After a short investigation, I fear that in order to compute the `element_indices`, we need to compute the neighbor elements explicitely, so that a binary search in the element list of the owner process can be performed. Only the calculation of the dual_faces can be skipped, but this will only be a small part of the total runtime.

But I also suspect that there are some further issues regarding elements created by t8_element_new, as their memory balance is not automatically checked, as it is with all manual calls to `T8_ALLOC`.

With regards to your current example: I adapted the current `step3` tutorial, so that `t8_step3_adapt_callback` just returns 0 and replaced `  forest = t8_step3_adapt_forest (forest);` by
```
  memory_usage(1);
  forest = t8_step3_adapt_forest (forest);
  memory_usage(1);
  forest = t8_step3_adapt_forest (forest);
  memory_usage(1);
  forest = t8_step3_adapt_forest (forest);
  memory_usage(1);
  forest = t8_step3_adapt_forest (forest);
  memory_usage(1);
```
This gave:
```
[t8] MEMORY USAGE: 15.258926 MB(16000144) malloc: 1.832031 MB reserved (93040 unused)
[t8] Into t8_forest_adapt from 8192 total elements
[t8] Done t8_forest_adapt with 8192 total elements
[t8] MEMORY USAGE: 15.259003 MB(16000224) malloc: 1.968750 MB reserved (236448 unused)
[t8] Into t8_forest_adapt from 8192 total elements
[t8] Done t8_forest_adapt with 8192 total elements
[t8] MEMORY USAGE: 15.259094 MB(16000320) malloc: 1.968750 MB reserved (236224 unused)
[t8] Into t8_forest_adapt from 8192 total elements
[t8] Done t8_forest_adapt with 8192 total elements
[t8] MEMORY USAGE: 15.259094 MB(16000320) malloc: 1.968750 MB reserved (236224 unused)
[t8] Into t8_forest_adapt from 8192 total elements
[t8] Done t8_forest_adapt with 8192 total elements
[t8] MEMORY USAGE: 15.259094 MB(16000320) malloc: 1.968750 MB reserved (236224 unused)
```
My understanding is that because a memory pool is used, the first call to adapt allocates a lot of memory that is not freed, but kept by the mempool. In the next call to adapt, no new allocs have to be performed, as the mempool gives back the stored memory.
This explains the stagnation of memory usage after the second call, but I cannot yet explain the difference caused by the second call of adapt.

**Comment by ackirby88** [comment]
I was able to confirm the same behavior using step_3 as you saw.
I will note that the memory_usage can be a little inconsistent between runs but overall insightful.

Now, I did a similar experiment but changed the adaption to include balance:
```
t8_forest_t
t8_step3_adapt_forest_2 (t8_forest_t forest)
{
  t8_forest_t         forest_adapt;

  struct t8_step3_adapt_data adapt_data = {
    {0.5, 0.5, 1},              /* Midpoints of the sphere. */
    0.2,                        /* Refine if inside this radius. */
    0.4                         /* Coarsen if outside this radius. */
  };

  t8_forest_init (&forest_adapt);
  t8_forest_set_adapt (forest_adapt, forest, t8_step3_adapt_callback, 0);
  t8_forest_set_ghost (forest_adapt, 1, T8_GHOST_FACES);
  t8_forest_set_balance (forest_adapt, NULL, 1);
  t8_forest_set_user_data (forest_adapt, &adapt_data);
  t8_forest_commit (forest_adapt);
    return forest_adapt;
}
```

Further, I ran 100 iterations (and set the t8/sc logging to `SC_LP_SILENT`):
```
Rank[0]: 3.481903 MB(3651040) malloc: 2.035156 MB reserved (0.193878 unused)
Rank[0]: 3.497162 MB(3667040) malloc: 2.707031 MB reserved (0.850494 unused)
Rank[0]: 3.497177 MB(3667056) malloc: 2.707031 MB reserved (0.850479 unused)
Rank[0]: 3.501083 MB(3671152) malloc: 2.707031 MB reserved (0.846573 unused)
Rank[0]: 3.502472 MB(3672608) malloc: 2.707031 MB reserved (0.845184 unused)
Rank[0]: 3.511490 MB(3682064) malloc: 2.707031 MB reserved (0.836166 unused)
Rank[0]: 3.512360 MB(3682976) malloc: 2.707031 MB reserved (0.835297 unused)
Rank[0]: 3.520233 MB(3691232) malloc: 2.839844 MB reserved (0.960236 unused)
Rank[0]: 3.522263 MB(3693360) malloc: 2.792969 MB reserved (0.911331 unused)
Rank[0]: 3.526474 MB(3697776) malloc: 2.792969 MB reserved (0.907120 unused)
Rank[0]: 3.539673 MB(3711616) malloc: 2.792969 MB reserved (0.893921 unused)
Rank[0]: 3.544281 MB(3716448) malloc: 2.792969 MB reserved (0.889313 unused)
Rank[0]: 3.546066 MB(3718320) malloc: 2.792969 MB reserved (0.887527 unused)
Rank[0]: 3.550674 MB(3723152) malloc: 2.792969 MB reserved (0.882919 unused)
Rank[0]: 3.559647 MB(3732560) malloc: 2.792969 MB reserved (0.873947 unused)
Rank[0]: 3.561295 MB(3734288) malloc: 2.792969 MB reserved (0.872299 unused)
Rank[0]: 3.566254 MB(3739488) malloc: 2.792969 MB reserved (0.867340 unused)
Rank[0]: 3.568222 MB(3741552) malloc: 2.792969 MB reserved (0.865372 unused)
Rank[0]: 3.570190 MB(3743616) malloc: 2.792969 MB reserved (0.863403 unused)
Rank[0]: 3.583679 MB(3757760) malloc: 2.792969 MB reserved (0.849915 unused)
Rank[0]: 3.584534 MB(3758656) malloc: 2.792969 MB reserved (0.849060 unused)
Rank[0]: 3.586151 MB(3760352) malloc: 2.792969 MB reserved (0.847443 unused)
Rank[0]: 3.591080 MB(3765520) malloc: 2.921875 MB reserved (0.971420 unused)
Rank[0]: 3.591019 MB(3765456) malloc: 2.898438 MB reserved (0.948044 unused)
Rank[0]: 3.600311 MB(3775200) malloc: 2.898438 MB reserved (0.938751 unused)
Rank[0]: 3.604813 MB(3779920) malloc: 2.898438 MB reserved (0.934250 unused)
Rank[0]: 3.604996 MB(3780112) malloc: 2.898438 MB reserved (0.934067 unused)
Rank[0]: 3.606384 MB(3781568) malloc: 2.898438 MB reserved (0.932678 unused)
Rank[0]: 3.607895 MB(3783152) malloc: 2.898438 MB reserved (0.931168 unused)
Rank[0]: 3.620514 MB(3796384) malloc: 2.898438 MB reserved (0.918549 unused)
Rank[0]: 3.620956 MB(3796848) malloc: 2.898438 MB reserved (0.918106 unused)
Rank[0]: 3.621246 MB(3797152) malloc: 2.898438 MB reserved (0.917816 unused)
Rank[0]: 3.626633 MB(3802800) malloc: 2.898438 MB reserved (0.912430 unused)
Rank[0]: 3.634338 MB(3810880) malloc: 2.898438 MB reserved (0.904724 unused)
Rank[0]: 3.634583 MB(3811136) malloc: 2.898438 MB reserved (0.904480 unused)
Rank[0]: 3.638626 MB(3815376) malloc: 2.898438 MB reserved (0.900436 unused)
Rank[0]: 3.638931 MB(3815696) malloc: 2.898438 MB reserved (0.900131 unused)
Rank[0]: 3.639633 MB(3816432) malloc: 2.898438 MB reserved (0.899429 unused)
Rank[0]: 3.652191 MB(3829600) malloc: 2.898438 MB reserved (0.886871 unused)
Rank[0]: 3.652100 MB(3829504) malloc: 2.898438 MB reserved (0.886963 unused)
Rank[0]: 3.652100 MB(3829504) malloc: 2.898438 MB reserved (0.886963 unused)
Rank[0]: 3.656204 MB(3833808) malloc: 2.898438 MB reserved (0.882858 unused)
Rank[0]: 3.656555 MB(3834176) malloc: 2.898438 MB reserved (0.882507 unused)
Rank[0]: 3.664276 MB(3842272) malloc: 2.898438 MB reserved (0.874786 unused)
Rank[0]: 3.670746 MB(3849056) malloc: 2.898438 MB reserved (0.868317 unused)
Rank[0]: 3.670731 MB(3849040) malloc: 2.898438 MB reserved (0.868332 unused)
Rank[0]: 3.670731 MB(3849040) malloc: 2.898438 MB reserved (0.868332 unused)
Rank[0]: 3.678436 MB(3857120) malloc: 2.898438 MB reserved (0.860626 unused)
Rank[0]: 3.682495 MB(3861376) malloc: 2.898438 MB reserved (0.856567 unused)
Rank[0]: 3.682663 MB(3861552) malloc: 2.898438 MB reserved (0.856400 unused)
Rank[0]: 3.682480 MB(3861360) malloc: 2.898438 MB reserved (0.856583 unused)
Rank[0]: 3.686600 MB(3865680) malloc: 3.031250 MB reserved (0.985275 unused)
Rank[0]: 3.695114 MB(3874608) malloc: 3.003906 MB reserved (0.949417 unused)
Rank[0]: 3.696274 MB(3875824) malloc: 3.003906 MB reserved (0.948257 unused)
Rank[0]: 3.701874 MB(3881696) malloc: 3.003906 MB reserved (0.942657 unused)
Rank[0]: 3.703415 MB(3883312) malloc: 2.960938 MB reserved (0.898148 unused)
Rank[0]: 3.703308 MB(3883200) malloc: 2.960938 MB reserved (0.898254 unused)
Rank[0]: 3.717499 MB(3898080) malloc: 2.960938 MB reserved (0.884064 unused)
Rank[0]: 3.717529 MB(3898112) malloc: 2.960938 MB reserved (0.884033 unused)
Rank[0]: 3.717819 MB(3898416) malloc: 2.960938 MB reserved (0.883743 unused)
Rank[0]: 3.721603 MB(3902384) malloc: 2.960938 MB reserved (0.880005 unused)
Rank[0]: 3.721634 MB(3902416) malloc: 2.960938 MB reserved (0.879929 unused)
Rank[0]: 3.729553 MB(3910720) malloc: 2.960938 MB reserved (0.872009 unused)
Rank[0]: 3.733292 MB(3914640) malloc: 2.960938 MB reserved (0.868271 unused)
Rank[0]: 3.733475 MB(3914832) malloc: 2.960938 MB reserved (0.868088 unused)
Rank[0]: 3.733231 MB(3914576) malloc: 2.960938 MB reserved (0.868332 unused)
Rank[0]: 3.741409 MB(3923152) malloc: 2.960938 MB reserved (0.860153 unused)
Rank[0]: 3.745316 MB(3927248) malloc: 3.089844 MB reserved (0.985153 unused)
Rank[0]: 3.745590 MB(3927536) malloc: 3.054688 MB reserved (0.949768 unused)
Rank[0]: 3.745544 MB(3927488) malloc: 3.054688 MB reserved (0.949768 unused)
Rank[0]: 3.750168 MB(3932336) malloc: 3.054688 MB reserved (0.945145 unused)
Rank[0]: 3.758087 MB(3940640) malloc: 3.054688 MB reserved (0.937225 unused)
Rank[0]: 3.758286 MB(3940848) malloc: 3.054688 MB reserved (0.937027 unused)
Rank[0]: 3.762085 MB(3944832) malloc: 3.054688 MB reserved (0.933228 unused)
Rank[0]: 3.761993 MB(3944736) malloc: 3.054688 MB reserved (0.933319 unused)
Rank[0]: 3.762100 MB(3944848) malloc: 3.054688 MB reserved (0.933258 unused)
Rank[0]: 3.774048 MB(3957376) malloc: 3.054688 MB reserved (0.921265 unused)
Rank[0]: 3.773926 MB(3957248) malloc: 3.054688 MB reserved (0.921387 unused)
Rank[0]: 3.774048 MB(3957376) malloc: 3.054688 MB reserved (0.921265 unused)
Rank[0]: 3.777847 MB(3961360) malloc: 3.054688 MB reserved (0.917465 unused)
Rank[0]: 3.777878 MB(3961392) malloc: 3.054688 MB reserved (0.917435 unused)
Rank[0]: 3.785782 MB(3969680) malloc: 3.054688 MB reserved (0.909531 unused)
Rank[0]: 3.789825 MB(3973920) malloc: 3.054688 MB reserved (0.905487 unused)
Rank[0]: 3.789612 MB(3973696) malloc: 3.054688 MB reserved (0.905701 unused)
Rank[0]: 3.789566 MB(3973648) malloc: 3.054688 MB reserved (0.905746 unused)
Rank[0]: 3.797409 MB(3981872) malloc: 2.960938 MB reserved (0.804153 unused)
Rank[0]: 3.801346 MB(3986000) malloc: 3.089844 MB reserved (0.929123 unused)
Rank[0]: 3.801605 MB(3986272) malloc: 2.960938 MB reserved (0.800003 unused)
Rank[0]: 3.805252 MB(3990096) malloc: 3.093750 MB reserved (0.929123 unused)
Rank[0]: 3.805267 MB(3990112) malloc: 3.093750 MB reserved (0.929108 unused)
Rank[0]: 3.813324 MB(3998560) malloc: 3.093750 MB reserved (0.921051 unused)
Rank[0]: 3.813126 MB(3998352) malloc: 3.093750 MB reserved (0.921249 unused)
Rank[0]: 3.817062 MB(4002480) malloc: 3.093750 MB reserved (0.917313 unused)
Rank[0]: 3.817032 MB(4002448) malloc: 3.093750 MB reserved (0.917343 unused)
Rank[0]: 3.817123 MB(4002544) malloc: 3.093750 MB reserved (0.917252 unused)
Rank[0]: 3.829391 MB(4015408) malloc: 3.093750 MB reserved (0.905029 unused)
Rank[0]: 3.829300 MB(4015312) malloc: 3.093750 MB reserved (0.905075 unused)
Rank[0]: 3.829147 MB(4015152) malloc: 3.093750 MB reserved (0.905228 unused)
Rank[0]: 3.833252 MB(4019456) malloc: 3.093750 MB reserved (0.901123 unused)
Rank[0]: 3.837036 MB(4023424) malloc: 2.960938 MB reserved (0.764526 unused)
```
As you can see, I think there is a memory leak in balance.
Can you confirm this behavior on your end?
I'll see if I can determine the potential leak in balance.

**Comment by ackirby88** [comment]
@lukasdreyer 
Okay, I tested it further. It seems the original `t8_step3_adapt_forest` with no ghosts or balance also has memory issues, which are passed onto each proceeding adapted forest. 

I compiled t8code with MPI disabled (--disable-mpi) and ran the following in step3:
```
  for(int i = 0; i < 50000; i++){
      memory_usage(i,1);
      forest = t8_step3_adapt_forest (forest);
  }
```
You can watch the memory grow over the iterations:
```
Step[    0]: 0.307129 MB(322048) malloc: 0.386719 MB reserved (0.079590 unused), Total = 0.386719
.
.
.
Step[50000]: 32.584381 MB(34167200) malloc: 33.386719 MB reserved (0.802338 unused), Total = 33.386719
```
However, I checked with Valgrind that the memory is completely freed with no errors after the final 
`t8_forest_unref (&forest);`.

Additionally, I tested the following:
```
for(int i = 0; i < 50000; i++){
      memory_usage(i+1,1);
      cmesh = t8_cmesh_new_hypercube_hybrid (comm, 0, 0);
      forest = t8_forest_new_uniform (cmesh, t8_scheme_new_default_cxx (), level, 0, comm);
      t8_forest_unref (&forest);
  }
```
The memory stays constant! `Rank[0]: 0.328522 MB(344480) malloc: 0.511719 MB reserved (0.184204 unused)`.

So one (or more) of the memory pools that is passed between the incoming and outgoing forest is having memory being added, but is properly freed with the final `t8_forest_unref`.

**Comment by lukasdreyer** [comment]
> @lukasdreyer Okay, I tested it further. It seems the original `t8_step3_adapt_forest` with no ghosts or balance also has memory issues, which are passed onto each proceeding adapted forest.
> 
> I compiled t8code with MPI disabled (--disable-mpi) and ran the following in step3:
> 
> ```
>   for(int i = 0; i < 50000; i++){
>       memory_usage(i,1);
>       forest = t8_step3_adapt_forest (forest);
>   }
> ```
> 
> You can watch the memory grow over the iterations:
> 
> ```
> Step[    0]: 0.307129 MB(322048) malloc: 0.386719 MB reserved (0.079590 unused), Total = 0.386719
> .
> .
> .
> Step[50000]: 32.584381 MB(34167200) malloc: 33.386719 MB reserved (0.802338 unused), Total = 33.386719
> ```
> 
> However, I checked with Valgrind that the memory is completely freed with no errors after the final `t8_forest_unref (&forest);`.

Is this run with a real refinement criterion? Because then for the 20 or so first refinement steps, we get lots more elements, therefore we also get a higher memory usage. After we reach the maximum refinement level, the memory should stay constant.

**Comment by lukasdreyer** [comment]
> As you can see, I think there is a memory leak in balance. Can you confirm this behavior on your end? I'll see if I can determine the potential leak in balance.

I was able to replicate this behaviour in balance on my end. I will also have a look if I can determine its root.

**Comment by ackirby88** [comment]
Nope, I set the refinement callback to return 0 at the top (and verified the elements remain constant).

**Comment by lukasdreyer** [comment]
> Nope, I set the refinement callback to return 0 at the top (and verified the elements remain constant).

Yeah, I could replicate that effect on my side as well! (The mere 5 that I tried out above were apparently not a big enough samplesize).

**Comment by lukasdreyer** [comment]
What I do find curious is that the memory usage does not increase with every call to `t8_step3_adapt_forest`, but only every few calls

**Comment by ackirby88** [comment]
Yes, this would likely be related to sc memory pools (e.g., sc_list) which reallocate when its full...

**Comment by lukasdreyer** [comment]
I think I found a first large culprit contributing to the memory leak in adapt: 

In `t8_forest_compute_desc` , memory is allocated for `first_desc` and `last_desc` for each tree, but apparently never freed.

I extended the `t8_forest_free_trees` function in `t8_forest.c`
```
static void
t8_forest_free_trees (t8_forest_t forest)
{
  t8_tree_t           tree;
  t8_locidx_t         jt, number_of_trees;

  T8_ASSERT (forest != NULL);
  T8_ASSERT (forest->committed);

  number_of_trees = forest->trees->elem_count;
  for (jt = 0; jt < number_of_trees; jt++) {
    tree = (t8_tree_t) t8_sc_array_index_locidx (forest->trees, jt);
    t8_element_array_reset (&tree->elements);
    t8_eclass_t eclass = t8_forest_get_tree_class(forest, jt);
    t8_eclass_scheme_c *scheme = forest->scheme_cxx->eclass_schemes[eclass];
    t8_element_destroy(scheme, 1, &tree->first_desc);
    t8_element_destroy(scheme, 1, &tree->last_desc);
  }
  sc_array_destroy (forest->trees);
}
```
and got most (but not all!) of the accumulating memory resolved.

**Comment by ackirby88** [comment]
Yep, I just found the same without seeing your comment until now!
Last issues are with balance...

**Comment by ackirby88** [comment]
What if (to be safe), you put a destroy into the `t8_element_new` function?
```
void
t8_default_scheme_common_c::t8_element_new (int length, t8_element_t **elem) const
{
  if(*elem != NULL) t8_element_destroy(length,elem);
  t8_default_mempool_alloc ((sc_mempool_t *) this->ts_context, length, elem);
}
```
This seems to work without explicitly calling the destroy for first_desc and last_desc.

**Comment by ackirby88** [comment]
@lukasdreyer 
I think the same issue exists in `t8_forest_copy_trees`...

**Comment by lukasdreyer** [comment]
> @lukasdreyer I think the same issue exists in `t8_forest_copy_trees`...

My first intuition is that this should also be covered by the addition of the 2 `t8_element_destroy` calls that I added to `t8_forest_free_trees` function above, but I will have a deeper look tomorrow

**Comment by lukasdreyer** [comment]
@ackirby88: I found some more missing t8_element_destroy statements. Have a look at #676.

But I don't seem to have found all of them yet, so I am still investigating.

**Comment by lukasdreyer** [comment]
> > @lukasdreyer I think the same issue exists in `t8_forest_copy_trees`...
> 
> My first intuition is that this should also be covered by the addition of the 2 `t8_element_destroy` calls that I added to `t8_forest_free_trees` function above, but I will have a deeper look tomorrow

Maybe my intuition was not right. I cannot yet pinpoint the solution, but it seems that with balance, not all tree->first/last_desc are freed. My guess is that this comes from the inermediate forests created during the commit balance process.

**Comment by ackirby88** [comment]
I was able to get the memory constant without balance after fixing the copy_trees function.
Agreed that the last problem is in balance creating the intermediate forests. You can use the memory_usage function inside there as well to get a closer look at where the problems are -- this is the approach I'm trying currently.

**Comment by lukasdreyer** [comment]
I pushed some new commits to #676.
With these changes, the memory is more or less constant for balance, but behaving quite erratically, jumping up and down, as you can see below.
I also checked that the number of calls to `t8_element_destroy` now equals the number of calls to `t8_element_new`.
I still want to check, that whenever the memorypool of a scheme is destroyed, that all elements were already given back to the memorypool explicitely.

```
1-10 :
[t8] MEMORY USAGE: 15.258926 MB(16000144) malloc: 1.832031 MB reserved (93040 unused)
[t8] MEMORY USAGE: 17.013596 MB(17840048) malloc: 2.546875 MB reserved (706640 unused)
[t8] MEMORY USAGE: 17.013840 MB(17840304) malloc: 2.546875 MB reserved (706384 unused)
[t8] MEMORY USAGE: 17.013870 MB(17840336) malloc: 2.546875 MB reserved (706432 unused)
[t8] MEMORY USAGE: 17.013947 MB(17840416) malloc: 2.546875 MB reserved (707024 unused)
[t8] MEMORY USAGE: 17.014465 MB(17840960) malloc: 2.546875 MB reserved (706480 unused)
[t8] MEMORY USAGE: 17.014725 MB(17841232) malloc: 2.546875 MB reserved (705616 unused)
[t8] MEMORY USAGE: 17.015884 MB(17842448) malloc: 2.546875 MB reserved (704752 unused)
[t8] MEMORY USAGE: 17.015884 MB(17842448) malloc: 2.546875 MB reserved (704992 unused)
[t8] MEMORY USAGE: 17.016602 MB(17843200) malloc: 2.546875 MB reserved (704000 unused)

```

```
251-260
[t8] MEMORY USAGE: 17.020950 MB(17847760) malloc: 2.546875 MB reserved (698928 unused)
[t8] MEMORY USAGE: 17.021011 MB(17847824) malloc: 2.546875 MB reserved (699616 unused)
[t8] MEMORY USAGE: 17.022766 MB(17849664) malloc: 2.546875 MB reserved (697776 unused)
[t8] MEMORY USAGE: 17.022064 MB(17848928) malloc: 2.546875 MB reserved (698512 unused)
[t8] MEMORY USAGE: 17.021210 MB(17848032) malloc: 2.546875 MB reserved (698864 unused)
[t8] MEMORY USAGE: 17.020950 MB(17847760) malloc: 2.546875 MB reserved (699088 unused)
[t8] MEMORY USAGE: 17.021027 MB(17847840) malloc: 2.546875 MB reserved (699600 unused)
[t8] MEMORY USAGE: 17.021027 MB(17847840) malloc: 2.546875 MB reserved (699600 unused)
[t8] MEMORY USAGE: 17.021011 MB(17847824) malloc: 2.546875 MB reserved (699616 unused)
[t8] MEMORY USAGE: 17.020950 MB(17847760) malloc: 2.546875 MB reserved (699088 unused)

```

```
501-510
[t8] MEMORY USAGE: 17.021622 MB(17848464) malloc: 2.546875 MB reserved (698976 unused) 
[t8] MEMORY USAGE: 17.023727 MB(17850672) malloc: 2.546875 MB reserved (696768 unused) 
[t8] MEMORY USAGE: 17.022324 MB(17849200) malloc: 2.546875 MB reserved (698240 unused) 
[t8] MEMORY USAGE: 17.021973 MB(17848832) malloc: 2.546875 MB reserved (698608 unused) 
[t8] MEMORY USAGE: 17.021973 MB(17848832) malloc: 2.546875 MB reserved (698608 unused) 
[t8] MEMORY USAGE: 17.021973 MB(17848832) malloc: 2.546875 MB reserved (698608 unused) 
[t8] MEMORY USAGE: 17.022324 MB(17849200) malloc: 2.546875 MB reserved (698240 unused) 
[t8] MEMORY USAGE: 17.023026 MB(17849936) malloc: 2.546875 MB reserved (697504 unused) 
[t8] MEMORY USAGE: 17.023026 MB(17849936) malloc: 2.546875 MB reserved (697504 unused) 
[t8] MEMORY USAGE: 17.021881 MB(17848736) malloc: 2.546875 MB reserved (698112 unused) 
```

```
991-1000
[t8] MEMORY USAGE: 17.024765 MB(17851760) malloc: 2.546875 MB reserved (695680 unused)
[t8] MEMORY USAGE: 17.024063 MB(17851024) malloc: 2.546875 MB reserved (696416 unused)
[t8] MEMORY USAGE: 17.025116 MB(17852128) malloc: 2.546875 MB reserved (695312 unused)
[t8] MEMORY USAGE: 17.025467 MB(17852496) malloc: 2.546875 MB reserved (694944 unused)
[t8] MEMORY USAGE: 17.024277 MB(17851248) malloc: 2.546875 MB reserved (695760 unused)
[t8] MEMORY USAGE: 17.024414 MB(17851392) malloc: 2.546875 MB reserved (696048 unused)
[t8] MEMORY USAGE: 17.024017 MB(17850976) malloc: 2.546875 MB reserved (695872 unused)
[t8] MEMORY USAGE: 17.024063 MB(17851024) malloc: 2.546875 MB reserved (696416 unused)
[t8] MEMORY USAGE: 17.024292 MB(17851264) malloc: 2.546875 MB reserved (695424 unused)
[t8] MEMORY USAGE: 17.024063 MB(17851024) malloc: 2.546875 MB reserved (696416 unused)
```

**Comment by lukasdreyer** [comment]
> The intermittence of the memory is due to MPI -- if you recompile in serial you see the usage as much more stable. There only remains a very small memory leak now (e.g., 0.311569 to 0.321243 MB over 5,000 iterations). Great bug finds!

Thank you! Recompiling in serial helped! After 30 or so iterations, the memory usage stayed constant until 5000 iterations.

> Also, on your commit changing the step_3: I think it would be best to make a new file (i.e., step3_adapt_memory) since you completely disabled the adaption feature by returning 0 in the tag function at the top.

This was currently only thought as a place for discussion, I will make a clean PR once all the tests run through.
