### ISSUE TITLE
Use more than 2 processes in testing

### ISSUE THREAD

**Issue by holke** [DLR-AMR/t8code#68]
The test runner is currently configured to use `mpirun -np 2`.
We should increase the number of parallel processes to at least 4.

This is configured in the variable `SC_MPI_TEST_FLAGS` or `T8_MPI_TEST_FLAGS`

**Comment by Davknapp** [comment]
Do you know where the variable is set?
Grepping for it only results in
`t8code/Makefile.am:LOG_COMPILER = @T8_MPIRUN@ @T8_MPI_TEST_FLAGS@`
and the search for T8_MPIRUN leads to the same, starting from a fresh download of t8code

**Comment by holke** [comment]
This is set in the sc library, so we would need to change it for sc and hence all packages using sc.

However, maybe writing a t8_mpi.m4 that overwrites the sc setting for T8_MPI_TEST_FLAG works? 

https://github.com/cburstedde/libsc/blob/master/config/sc_mpi.m4

**Comment by cburstedde** [comment]
> This is set in the sc library, so we would need to change it for sc and hence all packages using sc.
> 
> However, maybe writing a t8_mpi.m4 that overwrites the sc setting for T8_MPI_TEST_FLAG works? 
> 
> https://github.com/cburstedde/libsc/blob/master/config/sc_mpi.m4

It would not be hard to query an environment variable and/or the configure
line to make the number of test processes configurable.  We'd be happy to
consider proposed updates to sc.

**Comment by holke** [comment]
#1139 #1134 add configure options to control the number of processes that tests are run on.

The only remaining step is to add more than 2 processes to the CI.

Also related to #1088
