### ISSUE TITLE
t8_cmesh_set_tree_vertices has no effect on a t8_geometry_with_vertices subclass

### ISSUE THREAD

**Issue by CsatiZoltan** [DLR-AMR/t8code#800]
In the attached MWE, there is a bug that I fail to resolve for a long time.
The `t8_geometry_with_vertices` class constructor initializes the vertices of a cmesh tree to a null pointer:
https://github.com/DLR-AMR/t8code/blob/494c20e954d7250f3308a048882d48c18444d457/src/t8_geometry/t8_geometry_with_vertices.hxx#L51-L55
The vertices are associated with the tree by calling the `t8_cmesh_get_tree_vertices` function.
If you run the MWE as is, i.e. geometry created by the built-in `t8_geometry_linear_new` function, it successfully creates the .vtu file.
On the other hand, when I replace `geometry = t8_geometry_linear_new (2);` with my own subclass `t8_tri`, it results in a segfault.
I managed to figure out that the error comes from the `t8_geom_evaluate` method. This method is overriden in the `t8_geometry_linear` class as
https://github.com/DLR-AMR/t8code/blob/494c20e954d7250f3308a048882d48c18444d457/src/t8_geometry/t8_geometry_implementations/t8_geometry_linear.cxx#L43-L48
Here, `active_tree_vertices` is non-NULL, as expected.
So I inserted the
```cpp
t8_geom_compute_linear_geometry (active_tree_class, active_tree_vertices, ref_coords, num_coords, out_coords);
```
line to my `t8_tri::t8_geom_evaluate` method to mimic this behaviour.
To my surprise, `active_tree_vertices` is still a null pointer even though
```cpp
double *vertices = t8_cmesh_get_tree_vertices (cmesh, 0);
```
correctly reports the vertices.

Why does my `t8_tri` object not know about its vertices, while the t8_geometry_linear object does (while both being subclasses of `t8_geometry_with_vertices`)?

### File

[mwe.cxx.txt](https://github.com/DLR-AMR/t8code/files/13042700/mwe.cxx.txt)

**Comment by sandro-elsweijer** [comment]
Hey @CsatiZoltan,
it appears that your derived class overwrites the [`t8_geom_load_tree_data`](https://github.com/DLR-AMR/t8code/blob/6b868f1a3a3b82cc19c37efac96dc03795164a07/src/t8_geometry/t8_geometry_with_vertices.cxx#L32) function of `t8_geometry_with_vertices`. The vertices of each tree are saved as tree data and have to be therefore loaded, before a geometry is computed. Deleting line 38-41 in your MWE should the trick:
```cpp
void
t8_geom_load_tree_data (t8_cmesh_t cmesh, t8_gloidx_t gtreeid)
{
}
```

**Comment by CsatiZoltan** [comment]
Hi @sandro-elsweijer,
Thanks, it does the job!
The reason I overwrote `t8_geom_load_tree_data` is that the MWE was copied from an example file:
https://github.com/DLR-AMR/t8code/blob/6b868f1a3a3b82cc19c37efac96dc03795164a07/example/geometry/t8_example_geometries.cxx#L124-L127
I would rather not say how much time I spent on it...

**Comment by sandro-elsweijer** [comment]
Ah yes, but the example you used as a base is a geometry, which does not use any vertices and therefore does not need to load them.
The next time you have a question like this feel free to ask it on Mattermost. We look there more often and most of the time there are other people in it which have experienced the same problem as you do.
