### ISSUE TITLE
t8_cmesh_set_tree_vertices: input (..., t8_locidx_t ltree_id,...) bug (with fix)

### ISSUE THREAD

**Issue by ackirby88** [DLR-AMR/t8code#801]
Our team is working on assembling a cmesh from pre-partitioned mesh files.  
We believe there is a bug in the function input `t8_locidx_t ltree_id` for `t8_cmesh_set_tree_vertices`:  
https://github.com/DLR-AMR/t8code/blob/6b868f1a3a3b82cc19c37efac96dc03795164a07/src/t8_cmesh/t8_cmesh.c#L547-L556

**Specifically, the function input `t8_locidx_t ltree_id` should be `t8_gloidx_t gtree_id`.** 
Supporting evidence for using the **global tree id** is:  
1) `t8_stash_add_attribute`: input uses `t8_gloidx_t id`
2) `t8_cmesh_set_tree_class`: uses `t8_gloidx_t gtree_id`  

We've tested the switch to global id fixes our issues with cmesh construction.

**Comment by Davknapp** [comment]
Hey @ackirby88 ,

thanks again for this issue! We will have a look at it and fix it!

**Comment by lukasdreyer** [comment]
I agree, this should be a global index. Would you like to post the corresponding PR? Otherwise I could do it as well.

**Comment by ackirby88** [comment]
@lukasdreyer Please go ahead with the PR.  
There's a bunch of cmesh examples that have local tree index variables that may or may not need to be updated, so I wanted to defer to the DLR team for this.

**Comment by lukasdreyer** [comment]
I created a draft PR and will check whether the current use of the function is consistent with the new interface: #811
