### ISSUE TITLE
Add new interface function t8_element_equal

### ISSUE THREAD

**Issue by lukasdreyer** [DLR-AMR/t8code#824]
Currently, only one occurence of `t8_element_compare` actually checks the sign of the return value. All other occurences are rather interested in whether the elements are equal or not, and not the order in which they appear in the SFC.

Equality can be assessed without computing the expensive linearid by comparing the entries manually, or by a memcmp, with a new interface function `t8_element_equal`

**Comment by Davknapp** [comment]
Do we need an extra function for that? We could check for equality first by a 'memcmp', which returns 0, just like the current function and then do the linear-id check if memcmp doesn't return 0. That way we don't introduce a very similar function to 't8_element_compare' and profit from the faster 'memcmp'

**Comment by lukasdreyer** [comment]
I want to avoid the expensive calculation of linearid in the case that they are not equal, because I don't care in what order they are. That's why I don't agree that they are very similar, as their computational workload is very different.

**Comment by Davknapp** [comment]
Following our discussion on MM: I agree with you ;)

**Comment by holke** [comment]
Sounds like a typical optimization problem. If there are performance issues in an application that calls `compare` too often, then an extra implementation of `equal` would be beneficial.
If it just feels like overhead, but in reality only a fraction of runtime is spend in `compare` then its unnecessary to do the extra work.

**Comment by lukasdreyer** [comment]
One application that I could think of, although I have not measured it, are our tests.

**Comment by lukasdreyer** [comment]
For pyramids, the `is_family` call needed for deciding whether to call the coarsening callback depends on this comparison
