### ISSUE TITLE
t8_element_ref_coords has a bug

### ISSUE THREAD

**Issue by Davknapp** [DLR-AMR/t8code#830]
With commit [88121be1a2e1841174a01566d98fed88b2e03d40] bugfix in triangle ref coords computation, the following bug was introduced:

![vis_bug](https://github.com/DLR-AMR/t8code/assets/26361975/e778c785-ae73-4499-913d-6bc93037f16d)

The refined prisms pointing outwards of the cube should be pointing inwards. 

It can be reproduced by checking out onto the given commit and running the step 3 tutorial.

**Comment by lukasdreyer** [comment]
Observation: The bug seems to only occur when t8code is built with VTK.
When t8code is built with VTK, `t8_forest_vtk_point_to_element_ref_coords` and `t8_forest_element_from_ref_coords` are used to determine coords, whereas without VTK, `t8_forest_element_coordinate` is used

**Comment by lukasdreyer** [comment]
`t8_forest_vtk_point_to_element_ref_coords` seems to give out reference points in the wrong reference element
