### ISSUE TITLE
Make --enable-less-tests standard option for --enable-debug

### ISSUE THREAD

**Issue by lukasdreyer** [DLR-AMR/t8code#911]
Currently, there is a configuration option that enables the usage of less tests. I would like to have less tests enabled automatically when compiling with --enable-debug, to decrease runtime in this case.

**Comment by sandro-elsweijer** [comment]
But we have to keep in mind to implement a --disable-less-tests flag for the CI in this case

**Comment by holke** [comment]
I added the less-tests option to https://github.com/DLR-AMR/t8code/wiki/Configure-Options
