### ISSUE TITLE
std::sqrt is not constexpr enabled

### ISSUE THREAD

**Issue by dutkalex** [DLR-AMR/t8code#922]
Hi!
Trying to build t8code with LLVM 17.0 (using libc++), I got an error on the following line:
https://github.com/DLR-AMR/t8code/blob/6a5d5c9d51dfecaaf7b021de4aa58152b316d180/example/cmesh/t8_cmesh_geometry_examples.cxx#L171
According to cppreference, `std::sqrt` is not supposed to be usable in a constexpr context (see https://en.cppreference.com/w/cpp/numeric/math/sqrt). Editing the line to `const double inner_radius = sqrt (3.);` solved the issue on my machine. I don't think this change would impact anything else, do you want me to open a PR to fix this?
Best regards,
Alex

**Comment by holke** [comment]
Thanks for catching this!

Yes, a PR would be apprechiated.

**Comment by dutkalex** [comment]
Incoming...
From develop I suppose?

**Comment by holke** [comment]
From main.

Is there still a develop branch? I thought we deleted it...

**Comment by dutkalex** [comment]
Done. (https://github.com/dutkalex/t8code/tree/dutkalex-constexpr-fix)
